### Polish Uprising Seminar

title: The January Uprising
baseurl: /PolishUprisingSeminar # name of the repository
# repository: LemuelCushing/PolishUprisingSeminar

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md

collections:
 sections:
    output: true
    permalink: /:path/
 lists:
    output: true
    permalink: /:path/

# Comments
# disqus-shortname: webjeda-demo


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md
- /_sections/Summaries.md.backup

# gems: ['jekyll-github-metadata']
# gems: [jekyll-paginate-v2]
